// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOD2FjwWJ2dqy5XlQPtncFMHK_miExJw',
    appId: '1:134067109224:web:d0cc1fb1737e38cf2d2add',
    messagingSenderId: '134067109224',
    projectId: 'freak-flix-601a0',
    authDomain: 'freak-flix-601a0.firebaseapp.com',
    storageBucket: 'freak-flix-601a0.firebasestorage.app',
    measurementId: 'G-1KX6X9PD2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6kvpcKn0e3Uy6gqwujN4xSWSTRMWgXQ',
    appId: '1:134067109224:android:2f476ae5cf7876ff2d2add',
    messagingSenderId: '134067109224',
    projectId: 'freak-flix-601a0',
    storageBucket: 'freak-flix-601a0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuOD2FjwWJ2dqy5XlQPtncFMHK_miExJw',
    appId: '1:134067109224:web:aeb7ebd31ab0228e2d2add',
    messagingSenderId: '134067109224',
    projectId: 'freak-flix-601a0',
    authDomain: 'freak-flix-601a0.firebaseapp.com',
    storageBucket: 'freak-flix-601a0.firebasestorage.app',
    measurementId: 'G-HLGX7GRXSN',
  );
}
