// File generated by Antigravity as a placeholder.
// Run `flutterfire configure` to overwrite this file with real credentials.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnimplementedError('Web Firebase options not configured. Run "flutterfire configure".');
    }
    // Return dummy options to prevent compile errors, but runtime will fail if used before configure
    throw UnimplementedError('Firebase options not configured. Run "flutterfire configure".');
  }
}
