// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'missing_api_key',
      appId: dotenv.env['FIREBASE_APP_ID'] ?? 'missing_app_id',
      messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '134067109224',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'freak-flix-601a0',
      authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'freak-flix-601a0.firebaseapp.com',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'freak-flix-601a0.firebasestorage.app',
      measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID'] ?? 'G-1KX6X9PD2B',
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'missing_api_key',
      appId: dotenv.env['FIREBASE_APP_ID'] ?? 'missing_app_id',
      messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '134067109224',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'freak-flix-601a0',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'freak-flix-601a0.firebasestorage.app',
    );
  }

  static FirebaseOptions get windows {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'missing_api_key',
      appId: dotenv.env['FIREBASE_APP_ID'] ?? 'missing_app_id',
      messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '134067109224',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'freak-flix-601a0',
      authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'freak-flix-601a0.firebaseapp.com',
      storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'freak-flix-601a0.firebasestorage.app',
      measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID'] ?? 'G-HLGX7GRXSN',
    );
  }
}
